// Generated by CoffeeScript 1.6.3
var abuse_url, addendum, badge, download_name, download_url, hyperlink, hyperlink2, name, version, _ref;

abuse_url = $("[href$='ReportAbuse']").attr("href");

download_url = abuse_url.replace("/packages/", "/api/v2/package/").replace("/ReportAbuse", "");

_ref = abuse_url.split("/").slice(-3, -1), name = _ref[0], version = _ref[1];

download_name = "" + name + "-" + version + ".zip";

badge = $(".nuget-badge");

hyperlink = $("<a>", {
  href: download_url,
  download: download_name
}).append("<b>Download</b> " + download_name);

addendum = $('<p>').append("Or ").append(hyperlink);

addendum.insertAfter(badge);

hyperlink2 = $("<a>", {
  href: download_url
}).append("Download .zip");

$("[href$='/Download']").replaceWith(hyperlink2);
